### ISSUE TITLE
Failed to find files in something claiming to be podcast-1.0.dtd

### ISSUE THREAD

**Issue by doug-w** [freshe/poddl#15] opened 2023-10-15 03:29 UTC
Hi!  A feed that used to parse must have changed slightly:
https://files.manager-tools.com/files/public/feeds/manager-tools-basics.xml

I can see mp3s in the enclosure but on poddl 2023.08.18 it just says 'Error: No files found'

**Comment by freshe** [comment] 2023-10-15 10:56
Thanks! Should be fixed now. 
(That host now requires a user-agent present)

**Comment by doug-w** [comment] 2023-10-15 15:32
poddl 2023.10.15
https://www.fredrikblank.com/poddl/

Fetching URL: https://files.manager-tools.com/files/public/feeds/manager-tools-podcasts.xml
**Error: No files found**

Full command line:
./poddl https://files.manager-tools.com/files/public/feeds/manager-tools-podcasts.xml /storage/Podcasts/manager-tools

**Comment by freshe** [comment] 2023-10-15 16:28
Thanks again. Can reproduce on Linux, not macOS or Windows. Will investigate further

**Comment by doug-w** [comment] 2023-10-16 01:01
Thank you for the fast responses.  Really appreciate both the tool and how responsive you are!

**Comment by freshe** [comment] 2023-10-16 10:33
Thanks!
Think I found the issue. Linux distros with libcurl 7.x built-in fails on setting the user-agent.
I've compiled new Linux binaries with the latest version of libcurl.

**Comment by freshe** [comment] 2023-10-16 16:02
Turns out not a perfect solution.. The user needs to install dependencies now (libssl).
Reverted back. I'll keep this open in case I figure something else out for Linux.

**Comment by freshe** [comment] 2023-10-17 10:58
Compiled Linux binaries with curl 8 + embedtls statically linked. Calling it ok.

**Closed as completed by freshe** 2023-10-17 10:58 UTC
